"""empty message

Revision ID: 063e6118f130
Revises: c14e9ec71d67
Create Date: 2018-03-21 16:38:52.187437

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '063e6118f130'
down_revision = 'c14e9ec71d67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('article_papers')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article_papers',
    sa.Column('article_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('paper_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.article_id'], name='article_papers_ibfk_1'),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.paper_id'], name='article_papers_ibfk_2'),
    sa.PrimaryKeyConstraint('article_id', 'paper_id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
