"""Create hidden column and extend max length of institution

Revision ID: 163d2cbbb26c
Revises: ab2931050095
Create Date: 2018-01-12 16:32:01.226543

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '163d2cbbb26c'
down_revision = 'ab2931050095'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('hidden', sa.Boolean(), nullable=True, server_default='0'))
    op.alter_column('authors', 'Institution',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('authors', 'Institution',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.drop_column('articles', 'hidden')
    # ### end Alembic commands ###
