"""Add user_id to article papers to track annotator agreement

Revision ID: 451512b7ee9b
Revises: f17c4a77b188
Create Date: 2018-03-23 08:33:32.092803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '451512b7ee9b'
down_revision = 'f17c4a77b188'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article_papers', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'article_papers', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'article_papers', type_='foreignkey')
    op.drop_column('article_papers', 'user_id')
    # ### end Alembic commands ###
