"""empty message

Revision ID: 548c6b66b8e3
Revises: a12e86de073c
Create Date: 2018-01-12 14:44:29.005708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '548c6b66b8e3'
down_revision = 'a12e86de073c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article_papers',
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.article_id'], ),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.paper_id'], ),
    sa.PrimaryKeyConstraint('article_id', 'paper_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('article_papers')
    # ### end Alembic commands ###
