"""Add spam field for articles

Revision ID: 99311e4ac0fe
Revises: 163d2cbbb26c
Create Date: 2018-02-02 15:46:26.333146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99311e4ac0fe'
down_revision = '163d2cbbb26c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('spam', sa.Boolean(), server_default='0', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'spam')
    # ### end Alembic commands ###
