"""empty message

Revision ID: a12e86de073c
Revises: 
Create Date: 2018-01-05 13:42:18.768932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a12e86de073c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles',
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(collation='utf8_general_ci'), nullable=True),
    sa.Column('publish_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('article_id')
    )
    op.create_table('authors',
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('fullname', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('author_id')
    )
    op.create_table('papers',
    sa.Column('paper_id', sa.Integer(), nullable=False),
    sa.Column('doi', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=255, collation='utf8_general_ci'), nullable=True),
    sa.Column('abstract', sa.Text(collation='utf8_general_ci'), nullable=True),
    sa.Column('pubdate', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('paper_id'),
    sa.UniqueConstraint('doi')
    )
    op.create_table('entities',
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=128, collation='utf8_general_ci'), nullable=True),
    sa.Column('type', sa.String(length=32), nullable=True),
    sa.Column('start', sa.Integer(), nullable=True),
    sa.Column('end', sa.Integer(), nullable=True),
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.article_id'], ),
    sa.PrimaryKeyConstraint('entity_id')
    )
    op.create_table('paper_authors',
    sa.Column('paper_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['authors.author_id'], ),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.paper_id'], ),
    sa.PrimaryKeyConstraint('paper_id', 'author_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('paper_authors')
    op.drop_table('entities')
    op.drop_table('papers')
    op.drop_table('authors')
    op.drop_table('articles')
    # ### end Alembic commands ###
