"""Add annotation timer column to links

Revision ID: a2443af2c65e
Revises: 79dcf9aa4f15
Create Date: 2018-04-04 14:03:25.622267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2443af2c65e'
down_revision = '79dcf9aa4f15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article_papers', sa.Column('annotation_time', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article_papers', 'annotation_time')
    # ### end Alembic commands ###
