"""empty message

Revision ID: ab2931050095
Revises: 548c6b66b8e3
Create Date: 2018-01-12 14:58:00.148386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab2931050095'
down_revision = '548c6b66b8e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authors', sa.Column('Institution', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('authors', 'Institution')
    # ### end Alembic commands ###
