"""Add iaa column to articles

Revision ID: f940bf83cbef
Revises: a2443af2c65e
Create Date: 2018-04-07 17:39:52.282340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f940bf83cbef'
down_revision = 'a2443af2c65e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('do_iaa', sa.Boolean(), nullable=True, server_default=sa.schema.DefaultClause("0")))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'do_iaa')
    # ### end Alembic commands ###
